import img from "./report.png";
export const data = [
  {
    id: 1,
    title: "Point of Sale",
    //description: "View order, sales and usage reports",
    link: "/admin/reports",
    image: img,
    children: [
      {
        id: 1,
        title: "Customer Orders",
        //description: "View order, sales and usage reports",
        link: "/admin/customer-orders",
        image: img,
      },
      {
        id: 2,
        title: "Make a Sale",
        //description: "View order, sales and usage reports",
        link: "/admin/make-a-sale",
        image: img,
      },
      {
        id: 3,
        title: "Sale History",
        //description: "View order, sales and usage reports",
        link: "/admin/sale-history",
        image: img,
      },
      {
        id: 4,
        title: "Customer List",
        //description: "View order, sales and usage reports",
        link: "/admin/customer-list",
        image: img,
      },
      {
        id: 5,
        title: "Order List",
        //description: "View order, sales and usage reports",
        link: "/admin/order-list",
        image: img,
      },
      {
        id: 6,
        title: "Held Receipts",
        //description: "View order, sales and usage reports",
        link: "/admin/held-receipts",
        image: img,
      },
      {
        id: 7,
        title: "End of Day",
        //description: "View order, sales and usage reports",
        link: "/admin/end-of-day",
        image: img,
      },
      {
        id: 8,
        title: "Rewards",
        //description: "View order, sales and usage reports",
        link: "/admin/rewards",
        image: img,
      },
    ],
  },
  {
    id: 1,
    title: "Purchasing",
    //description: "View order, sales and usage reports",
    link: "/admin/reports",
    image: img,
    children: [
      {
        id: 1,
        title: "Sale History",
        //description: "View order, sales and usage reports",
        link: "/admin/sale-history",
        image: img,
      },
      {
        id: 2,
        title: "Point of Sale",
        //description: "View order, sales and usage reports",
        link: "/admin/reports",
        image: img,
      },
    ],
  },
  {
    id: 1,
    title: "Staff Management",
    //description: "View order, sales and usage reports",
    link: "/admin/reports",
    image: img,
    children: [
      {
        id: 1,
        title: "Point of Sale",
        //description: "View order, sales and usage reports",
        link: "/admin/reports",
        image: img,
      },
      {
        id: 2,
        title: "Point of Sale",
        //description: "View order, sales and usage reports",
        link: "/admin/reports",
        image: img,
      },
    ],
  },
];
